// Package db provides a database adapter interface for hot-swappable SQLite implementations.
//
// This allows switching between different SQLite drivers (modernc.org/sqlite, ncruces/go-sqlite3)
// without changing the code that uses the database. This is particularly useful for:
//   - Using sqlite-vec extension with ncruces driver for native vector search
//   - Testing with in-memory databases
//   - Future driver upgrades
package db

import (
	"context"
	"database/sql"
)

// DB is the main database interface matching the subset of *sql.DB methods we use.
// Implementations can wrap different SQLite drivers.
type DB interface {
	// Query executes a query that returns rows.
	Query(query string, args ...any) (Rows, error)

	// QueryContext executes a query with context.
	QueryContext(ctx context.Context, query string, args ...any) (Rows, error)

	// QueryRow executes a query expected to return at most one row.
	QueryRow(query string, args ...any) Row

	// QueryRowContext executes a query with context.
	QueryRowContext(ctx context.Context, query string, args ...any) Row

	// Exec executes a query without returning rows.
	Exec(query string, args ...any) (Result, error)

	// ExecContext executes a query with context.
	ExecContext(ctx context.Context, query string, args ...any) (Result, error)

	// Begin starts a transaction.
	Begin() (Tx, error)

	// BeginTx starts a transaction with context and options.
	BeginTx(ctx context.Context, opts *sql.TxOptions) (Tx, error)

	// Close closes the database connection.
	Close() error

	// Ping verifies a connection to the database is still alive.
	Ping() error

	// PingContext verifies with context.
	PingContext(ctx context.Context) error
}

// Tx represents a database transaction.
type Tx interface {
	// Query executes a query that returns rows.
	Query(query string, args ...any) (Rows, error)

	// QueryRow executes a query expected to return at most one row.
	QueryRow(query string, args ...any) Row

	// Exec executes a query without returning rows.
	Exec(query string, args ...any) (Result, error)

	// Prepare creates a prepared statement.
	Prepare(query string) (Stmt, error)

	// Commit commits the transaction.
	Commit() error

	// Rollback aborts the transaction.
	Rollback() error
}

// Stmt represents a prepared statement.
type Stmt interface {
	// Exec executes the prepared statement.
	Exec(args ...any) (Result, error)

	// Query executes the prepared statement and returns rows.
	Query(args ...any) (Rows, error)

	// QueryRow executes the prepared statement and returns at most one row.
	QueryRow(args ...any) Row

	// Close closes the statement.
	Close() error
}

// Rows is the result of a query returning multiple rows.
type Rows interface {
	// Next prepares the next row for reading.
	Next() bool

	// Scan copies the columns from the current row into dest.
	Scan(dest ...any) error

	// Close closes the rows.
	Close() error

	// Err returns the error, if any, encountered during iteration.
	Err() error

	// Columns returns the column names.
	Columns() ([]string, error)
}

// Row is the result of a query expecting a single row.
type Row interface {
	// Scan copies the columns into dest.
	Scan(dest ...any) error

	// Err returns the error from the query.
	Err() error
}

// Result summarizes an executed SQL command.
type Result interface {
	// LastInsertId returns the integer generated by the database.
	LastInsertId() (int64, error)

	// RowsAffected returns the number of rows affected.
	RowsAffected() (int64, error)
}

// ExtendedDB extends DB with optional vector search capabilities.
// Implementations that support sqlite-vec can implement this interface.
type ExtendedDB interface {
	DB

	// VectorSearchAvailable returns true if native vector search is supported.
	VectorSearchAvailable() bool

	// CreateVectorTable creates a vec0 virtual table for vector storage.
	// dimensions specifies the vector size (e.g., 768 for nomic-embed-text).
	// Returns an error if vector search is not available.
	CreateVectorTable(tableName string, dimensions int) error

	// InsertVector inserts a vector into a vec0 table.
	InsertVector(tableName string, vector []float32) (int64, error)

	// SearchKNN performs k-nearest-neighbor search on a vec0 table.
	// Returns row IDs and distances sorted by distance ascending.
	SearchKNN(tableName string, query []float32, k int) ([]VectorResult, error)
}

// VectorResult represents a result from KNN search.
type VectorResult struct {
	RowID    int64
	Distance float32
}

// Driver identifies a SQLite driver implementation.
type Driver string

const (
	// DriverModernc uses modernc.org/sqlite (pure Go, no CGO, no extensions).
	DriverModernc Driver = "modernc"

	// DriverNcruces uses ncruces/go-sqlite3 (WASM-based, supports extensions).
	DriverNcruces Driver = "ncruces"

	// DriverMattn uses mattn/go-sqlite3 (CGO, full extension support).
	DriverMattn Driver = "mattn"
)

// Config holds database configuration options.
type Config struct {
	// Driver specifies which SQLite implementation to use.
	Driver Driver

	// Path is the database file path. Use ":memory:" for in-memory database.
	Path string

	// EnableWAL enables Write-Ahead Logging for better concurrency.
	EnableWAL bool

	// VectorDimensions specifies the embedding vector size.
	// If > 0 and driver supports it, vector tables will be created.
	VectorDimensions int
}

// DefaultConfig returns a Config with sensible defaults.
func DefaultConfig(path string) Config {
	return Config{
		Driver:    DriverModernc,
		Path:      path,
		EnableWAL: true,
	}
}
